StudentJournal/StudentJournal/urls.py
from django.contrib import admin
from django.urls import path
import scheduling.views
import users.views
import grades_nonattendance.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', users.views.login_user),
    path('logout/', users.views.logout_user),
    path('teachers/', users.views.teachers_view),
    path('teachers/add_discipline/', users.views.add_discipline),
    path('teachers/add_discipline_to_teacher/', users.views.add_discipline_to_teacher),
    path('teachers/detach_discipline/<int:discipline_record_id>/', users.views.detach_discipline),
    path('students/', users.views.students_view),
    path('users/<int:user_id>/', users.views.user_info),
    path('users/<int:user_id>/edit/', users.views.user_edit),
    path('students/non-attendance-report/<int:student_id>/<int:term>/', grades_nonattendance.views.nonatt_report),
    path('students/grades-report/<int:student_id>/<int:term>/', grades_nonattendance.views.grades_report),
    path('account/', users.views.account),
    path('classes/', users.views.classes),
    path('classes/<int:class_id>/', users.views.class_info),
    path('classes/<int:class_id>/advance/', users.views.class_advance),
    path('classes/all_classes_advance/', users.views.all_classes_advance),
    path('classes/studied_disciplines/<int:class_num>/', users.views.studied_disciplines),
    path('schedule/create/<int:class_id>/', scheduling.views.create_schedule),
    path('schedule/edit_bell_quarter/', scheduling.views.bell_quarter_edit),
    path('schedule/teacher_schedule/<int:teacher_id>/<int:term>/', scheduling.views.teacher_schedule),
    path('schedule/', scheduling.views.schedule_menu),
    path('discipline_teacher/<int:discipline_id>/', scheduling.views.get_teachers_for_discipline),
    path('discipline_choices/<int:class_id>/<int:term>/', scheduling.views.discipline_choices),
    path('schedule/student_journal/<str:week_start_date>/<str:week_end_date>/', scheduling.views.student_journal),
    path('download_lesson_materials/<int:lesson_id>/', grades_nonattendance.views.download_lesson_materials),
    path('delete_lesson_materials/<int:lesson_id>/', grades_nonattendance.views.delete_lesson_materials),
    path('schedule/class_journal/<str:class_id>/<str:discipline_id>/<str:term>/', grades_nonattendance.views.class_journal),
    path('schedule/get_lesson/<int:lesson_id>/', grades_nonattendance.views.get_lesson),
    path('schedule/set_homework/<int:lesson_id>/', grades_nonattendance.views.set_homework),
    path('', users.views.index)
]

StudentJournal/scheduling/models.py
from django.db import models
from users.models import DisciplineTeacher, ClassCode

class LessonSchedule(models.Model):
    discipline_teacher = models.ForeignKey(DisciplineTeacher, on_delete=models.CASCADE)
    lesson_holding_datetime_start = models.DateTimeField()
    lesson_holding_datetime_end = models.DateTimeField()
    class_code = models.ForeignKey(ClassCode, on_delete=models.CASCADE)
    homework = models.CharField(max_length=255, blank=True, null=True)
    lesson_material_file = models.FileField(upload_to="materials", null=True, blank=True)
    sequence_num = models.SmallIntegerField()
    term_num = models.SmallIntegerField()
    classroom = models.CharField(max_length=5, null=False, blank=False)

    class Meta:
        unique_together = (('lesson_holding_datetime_start', 'class_code'),
                           ('lesson_holding_datetime_start', 'discipline_teacher'),
                           ('lesson_holding_datetime_start', 'classroom'),)
        permissions = (
            ('can_view_student_journal', 'Can view student journal'),
            ('can_view_class_journal', 'Can view class journal'),
            ('can_give_homework', 'Can give homework to class'),
        )

StudentJournal/users/models.py
from django.db import models
from django.contrib.auth.models import (
    AbstractBaseUser,
    PermissionsMixin,
    BaseUserManager,
)
from django.core.exceptions import ValidationError


class UserManager(BaseUserManager):
    def create_user(self, username, email, password, **extra_fields):
        if not username:
            raise ValueError("The Username must be set")
        if not email:
            raise ValueError("The Email must be set")
        email = self.normalize_email(email)
        user = self.model(username=username, **extra_fields)
        user.set_password(password)
        user.save()

        return user

    def create_superuser(self, username, email, password, **extra_fields):
        extra_fields.setdefault("is_superuser", True)
        extra_fields.setdefault("is_staff", True)
        if extra_fields.get("is_superuser") is not True:
            raise ValueError("Superuser must have is_superuser=True.")
        return self.create_user(username, email, password, **extra_fields)


class AppUser(AbstractBaseUser, PermissionsMixin):
    username = models.CharField(max_length=50, unique=True)
    first_name = models.CharField(max_length=50, null=True, blank=False)
    last_name = models.CharField(max_length=50, null=True, blank=False)
    patronym = models.CharField(max_length=50, null=True, blank=True)
    email = models.EmailField(max_length=50, unique=True)
    age = models.IntegerField(null=True)
    date_of_birth = models.DateTimeField(null=True, blank=False)
    is_staff = models.BooleanField(default=False)

    objects = UserManager()

    EMAIL_FIELD = "email"
    USERNAME_FIELD = "username"
    REQUIRED_FIELDS = ["email"]

    def __str__(self) -> str:
        return f"{self.last_name} {self.first_name} {self.patronym}"


class Parents(models.Model):
    student = models.OneToOneField(
        AppUser, on_delete=models.CASCADE, related_name="student_to_parents"
    )
    mother = models.ForeignKey(
        AppUser,
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name="mother_to_parents",
    )
    father = models.ForeignKey(
        AppUser,
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name="father_to_parents",
    )

    class Meta:
        unique_together = (("student", "father", "mother"),)


class DisciplineName(models.Model):
    discipline_name = models.CharField(max_length=50, unique=True)

    def __str__(self) -> str:
        return self.discipline_name


class DisciplineTeacher(models.Model):
    discipline = models.ForeignKey(DisciplineName, on_delete=models.CASCADE, related_name="discipline_to_teacher")
    teacher = models.ForeignKey(AppUser, on_delete=models.CASCADE, related_name="teacher_to_discipline")

    class Meta:
        unique_together = (("teacher", "discipline"),)


class ClassCode(models.Model):
    STUDYING = "ST"
    GRADUATED = "GR"
    STATUS_CHOICES = [
        (STUDYING, "Обучается"),
        (GRADUATED, "Выпущен"),
    ]

    class_code = models.CharField(max_length=3)
    homeroom_teacher = models.ForeignKey(AppUser, on_delete=models.CASCADE, related_name="homeroom_teacher_to_class")
    status = models.CharField(max_length=2, choices=STATUS_CHOICES, default=STUDYING)
    graduated_year = models.IntegerField(null=True)

    def clean(self):
        super().clean()
        if self.status == self.STUDYING:
            if (
                ClassCode.objects.filter(
                    class_code=self.class_code, status=self.STUDYING
                )
                .exclude(pk=self.pk)
                .exists()
            ):
                raise ValidationError(
                    "Такой класс уже существует в системе и ещё не выпустился."
                )

    def save(self, *args, **kwargs):
        self.clean()
        super().save(*args, **kwargs)

    def __str__(self) -> str:
        return self.class_code


class ClassStudent(models.Model):
    class_code = models.ForeignKey(ClassCode, on_delete=models.CASCADE)
    student = models.ForeignKey(AppUser, on_delete=models.CASCADE, related_name="student_to_class")

    class Meta:
        unique_together = (("class_code", "student"),)


class ClassDisciplines(models.Model):
    class_num = models.SmallIntegerField(null=False, blank=False, unique=True)
    studied_disciplines = models.ManyToManyField(DisciplineName, blank=True)

StudentJournal/users/forms.py
from django import forms
from django.forms import ModelForm
from .models import AppUser, DisciplineName, ClassCode, ClassDisciplines
from bootstrap_datepicker_plus.widgets import DatePickerInput
from users.methods.defs import num_years

class LoginForm(forms.Form):
    error_css_class = 'text_danger'
    username = forms.CharField(label="", widget=forms.TextInput(attrs={"placeholder": "Имя пользователя", "class": "form-control mb-3 mt-3"}))
    password = forms.CharField(label="", widget=forms.PasswordInput(attrs={"placeholder": "Пароль",  "class": "form-control mb-3 mt-3"}))


class UserForm(ModelForm):
    def save(self, commit=True):
        instance = super(UserForm, self).save(commit=False)
        instance.age = num_years(self.cleaned_data["date_of_birth"])
        instance.set_password(self.cleaned_data["password"])
        if commit:
            instance.save()
        return instance

    class Meta:
        model = AppUser
        fields = ["username", "password", "first_name", "last_name", "patronym", "email", "date_of_birth"]
        labels = {
            "username": "Имя пользователя:",
            "password": "Пароль:",
            "first_name": "Имя:",
            "last_name": "Фамилия:",
            "patronym": "Отчество:",
            "email": "Электронная почта:",
            "date_of_birth": "Дата рождения:"
        }
        widgets = {
            "username": forms.TextInput(attrs={'placeholder': 'Введите имя пользователя...', 'class':'mb-1'}),
            "password": forms.PasswordInput(attrs={'placeholder': 'Введите пароль...', 'class':'mb-1'}),
            "first_name": forms.TextInput(attrs={'placeholder': 'Введите имя...', 'class':'mb-1'}),
            "last_name": forms.TextInput(attrs={'placeholder': 'Введите фамилию...', 'class':'mb-1'}),
            "patronym": forms.TextInput(attrs={'placeholder': 'Введите отчество...', 'class':'mb-1'}),
            "email": forms.TextInput(attrs={'placeholder': 'Введите адрес электронной почты...', 'class':'mb-1'}),
            "date_of_birth": DatePickerInput(attrs={'placeholder': 'Укажите дату рождения...', 'class':'mb-1'})
        }


class DisciplineNameForm(ModelForm):
    class Meta:
        model = DisciplineName
        fields = ["discipline_name"]
        labels = {
            'discipline_name': 'Название предмета:'
        }
        widgets = {
            'discipline_name': forms.TextInput(attrs={'placeholder': 'Введите название предмета...', 'class':'mb-1'})
        }


class ClassCodeForm(ModelForm):
    class Meta:
        model = ClassCode
        fields = ["class_code"]
        labels = {
            'class_code': 'Код класса:'
        }
        widgets = {
            'class_code': forms.TextInput(attrs={'placeholder': 'Введите код класса...', 'class':'mb-1'})
        }

    def is_valid(self) -> bool:
        valid = super().is_valid()
        format_valid = True
        unique_valid = True

        cyrillic_symbols = 'абвгдеёжзийклмнопрстуфхцчшщъыьэюя'.upper()

        class_code = self.cleaned_data.get("class_code")
        paral = class_code[-1]
        class_num = class_code[:-1]

        if paral not in cyrillic_symbols or not class_num.isnumeric() or int(class_num) < 1 or int(class_num) > 11:
            self.add_error("class_code", "Класс введен в неверном формате")
            format_valid = False

        if ClassCode.objects.filter(class_code=class_code).exists():
            self.add_error("class_code", "Такой класс уже существует")
            unique_valid = False

        return valid and format_valid and unique_valid

class ClassDisciplinesForm(ModelForm):
    class Meta:
        model = ClassDisciplines
        fields = ["class_num", "studied_disciplines"]
        labels = {
            "class_num": "Целая часть номера класса:",
            "studied_disciplines": "Изучаемые дисциплины"
        }

    class_num = forms.IntegerField(widget=forms.HiddenInput)
    studied_disciplines = forms.ModelMultipleChoiceField(
        queryset=DisciplineName.objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )

StudentJournal/users/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    {% load static %}
    {% load django_bootstrap5 %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
    {% bootstrap_javascript %}
    {% bootstrap_css %} 
    {% load filters %}
    
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>Дневник школьника</title>
</head>
<body>
    {% block navbar %}
    {% endblock navbar %}

    {% block content %}
    {% endblock content %}
</body>
</html>

StudentJournal/users/templates/class_info.html
{% extends "index.html" %}
{% load django_bootstrap5 %}
{% load static %}
{% load filters %}

{% block content %}
<div class="container pt-3 pb-3">
    <div class="row">
        <div class="col-md-4">
            <h4>Общая информация</h4>
            <p>Класс {{ students_class.class_code }}</p>
            <p>Количество учеников в классе: {{ students_records|length }}</p>
            <p>Классный руководитель: {{students_class.homeroom_teacher.first_name}}
                {{students_class.homeroom_teacher.last_name}} {{students_class.homeroom_teacher.patronym}}</p>
            {% if perms.users.change_classcode %}
            <a href="/classes/{{ students_class.id }}/advance" type="button" class="btn btn-danger">Перевести учеников в следующий класс</a>
            {% endif %}
        </div>
    </div>
    <div class="row pt-3">
        <h4>Список учеников</h4>
        <div class="col">
            <table class="table table-striped">
                <thead>
                    <th>Ф.И.О</th>
                    <th>Email</th>
                    <th>Возраст</th>
                    <th>Дата рождения</th>
                </thead>
                <tbody>
                    {% for student_record in students_records %}
                    <tr>
                        <td>
                            <a href="/users/{{ student_record.student.id }}">{{ student_record.student.first_name }} {{ student_record.student.last_name }} {{ student_record.student.patronym }}</a> 
                        </td>
                        <td>
                            {{ student_record.student.email }}
                        </td>
                        <td>
                            {{ student_record.student.age }}
                        </td>
                        <td>
                            {{ student_record.student.date_of_birth.date }}
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

StudentJournal/users/templates/classes.html
{% extends "index.html" %}
{% load django_bootstrap5 %}
{% load static %}
{% load filters %}

{% block content %}
<div class="container pt-3 pb-3">
	{% if perms.users.add_classcode %}
	<div class="row">
		<div class="col-md-4">
			<h4>Добавление нового класса</h4>
			<form action="/classes/" method="post" class="form" autocomplete="off">
				{% csrf_token %}
				{% bootstrap_form class_code_form %}
				<label class="pb-3 me-3" for="teacher_select">Выберите классного руководителя:</label>
				<select style="display: inline-block;" class="form_select" name="teacher_select" id="teacher_select">
					{% for teacher in teachers %}
					<option value="{{teacher.id}}">{{teacher}}
					</option>
					{% endfor %}
				</select>
				<button type="submit" class="btn btn-light">Сохранить</button>
			</form>
		</div>
		<div class="col-md-4">
			<a id="id_studied_disciplines_link" href="#" class="link-primary">Настроить изучаемые предметы для класса</a>
			<select class="inline" onchange="updateStudiedDisciplinesLink()" name="class_num_select" id="id_class_num_select">
				<option value>--</option>
				<option value="1">1</option>
				<option value="2">2</option>
				<option value="3">3</option>
				<option value="4">4</option>
				<option value="5">5</option>
				<option value="6">6</option>
				<option value="7">7</option>
				<option value="8">8</option>
				<option value="9">9</option>
				<option value="10">10</option>
				<option value="11">11</option>
			</select>
		</div>
		{% if perms.users.change_classcode %}
		<div class="col-md-4">
			<a type="button" class="btn btn-danger" href="/classes/all_classes_advance">Перевести все классы на
				следующий
				год</a>
		</div>
		{% endif %}
	</div>
	{% endif %}
	<div class="row">
		<div class="col">
			<h4 class="mt-3">Список классов:</h4>
			<label for="id_filter_input">Поиск по таблице:</label>
			<input title="Поиск по таблице" placeholder="Введите Ф.И.О., статус или класс..."
			class="form-control w-50 mb-3 mt-3" id="id_filter_input" type="text" onkeyup="filterTable()">
			<table id="id_filtered_table" class="table table-striped">
				<thead>
					<th scope="col">Класс</th>
					<th scope="col">Количество учеников</th>
					<th scope="col">Классный руководитель</th>
					<th scope="col">Статус</th>
				</thead>
				<tbody>
					{% for class in classes %}
					<tr>
						<td>
							<a class="link-primary" href="/classes/{{ class.id }}">{{ class.class_code }}</a>
						</td>
						<td>
							{{ students_classes_dict|get_item:class|length }}
						</td>
						<td>
							<a href="/users/{{ class.homeroom_teacher.id }}">{{ class.homeroom_teacher }}</a>
						</td>
						<td>
							{{ class.get_status_display }} 
							{% if class.graduated_year %}
								({{ class.graduated_year }} г.)
							{% endif %}
						</td>
					</tr>
					{% endfor %}
				</tbody>
			</table>
		</div>
	</div>
</div>
<script src="{% static 'js/filter.js' %}"></script>
<script>
	const classNumSelect = document.getElementById("id_class_num_select");
	const studiedDisciplinesLink = document.getElementById("id_studied_disciplines_link");

	function updateStudiedDisciplinesLink() {
		if (classNumSelect.value) {
			let classNumValue = classNumSelect.value;

			studiedDisciplinesLink.href = "/classes/studied_disciplines/" + classNumValue +"/";
		}
		else {
			studiedDisciplinesLink.href = "#";
		}
	}
</script>
{% endblock %}

StudentJournal/users/templates/index.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% load static %}
{% load filters %}
{{ form.media }}

{% block navbar %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="/">Дневник школьника</a>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                {% if perms.users.add_appuser %}
                <li class="nav-item">
                    <a class="nav-link active" href="/teachers/">Учителя</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="/students/">Ученики</a>
                </li>
                {% endif %}
                {% if perms.users.view_classcode %}
                <li class="nav-item">
                    <a class="nav-link active" href="/classes/">Классы</a>
                </li>
                {% endif %}
                {% if perms.scheduling.can_view_class_journal and not perms.scheduling.add_lessonschedule %}
                <li class="nav-item">
                    <a class="nav-link active" href="/schedule/">Классный журнал</a>
                </li>
                {% elif perms.scheduling.add_lessonschedule %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle active" href="#" id="navbarDropdown" role="button"
                        data-bs-toggle="dropdown" aria-expanded="false">
                        Управление расписанием
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="/schedule/">Составление расписания и журналы</a></li>
                        <li><a class="dropdown-item" href="/schedule/edit_bell_quarter/">Звонки и четверти</a></li>
                    </ul>
                </li>
                {% endif %}
                {% if perms.scheduling.can_view_student_journal and not request.user.is_superuser %}
                <li class="nav-item">
                    <a name="student_journal_link" id="id_student_journal_link" class="nav-link active"
                        href="/schedule/student_journal/{% current_monday %}/{% current_sunday %}/">Дневник</a>
                </li>
                {% endif %}
                {% if request.user|has_group:"student" %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle active" href="#" id="navbarDropdown" role="button"
                        data-bs-toggle="dropdown" aria-expanded="false">
                        Отчет по среднему баллу
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="/students/grades-report/{{ request.user.id }}/1/">за первую
                                четверть</a></li>
                        <li><a class="dropdown-item" href="/students/grades-report/{{ request.user.id }}/2/">за вторую
                                четверть</a></li>
                        <li><a class="dropdown-item" href="/students/grades-report/{{ request.user.id }}/3/">за третью
                                четверть</a></li>
                        <li><a class="dropdown-item" href="/students/grades-report/{{ request.user.id }}/4/">за
                                четвертую четверть</a></li>
                    </ul>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle active" href="#" id="navbarDropdown" role="button"
                        data-bs-toggle="dropdown" aria-expanded="false">
                        Отчет по посещаемости
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="/students/non-attendance-report/{{ request.user.id }}/1/">за первую
                                четверть</a></li>
                        <li><a class="dropdown-item" href="/students/non-attendance-report/{{ request.user.id }}/2/">за вторую
                                четверть</a></li>
                        <li><a class="dropdown-item" href="/students/non-attendance-report/{{ request.user.id }}/3/">за третью
                                четверть</a></li>
                        <li><a class="dropdown-item" href="/students/non-attendance-report/{{ request.user.id }}/4/">за
                                четвертую четверть</a></li>
                    </ul>
                </li>
                {% elif request.user|has_group:"parent" %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle active" href="#" id="navbarDropdown" role="button"
                        data-bs-toggle="dropdown" aria-expanded="false">
                        Отчет по среднему баллу
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="/students/grades-report/{% get_child_id request.user.id %}/1/">за первую
                                четверть</a></li>
                        <li><a class="dropdown-item" href="/students/grades-report/{% get_child_id request.user.id %}/2/">за вторую
                                четверть</a></li>
                        <li><a class="dropdown-item" href="/students/grades-report/{% get_child_id request.user.id %}/3/">за третью
                                четверть</a></li>
                        <li><a class="dropdown-item" href="/students/grades-report/{% get_child_id request.user.id %}/4/">за
                                четвертую четверть</a></li>
                    </ul>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle active" href="#" id="navbarDropdown" role="button"
                        data-bs-toggle="dropdown" aria-expanded="false">
                        Отчет по посещаемости
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="/students/non-attendance-report/{% get_child_id request.user.id %}/1/">за первую
                                четверть</a></li>
                        <li><a class="dropdown-item" href="/students/non-attendance-report/{% get_child_id request.user.id %}/2/">за вторую
                                четверть</a></li>
                        <li><a class="dropdown-item" href="/students/non-attendance-report/{% get_child_id request.user.id %}/3/">за третью
                                четверть</a></li>
                        <li><a class="dropdown-item" href="/students/non-attendance-report/{% get_child_id request.user.id %}/4/">за
                                четвертую четверть</a></li>
                    </ul>
                </li>
                {% endif %}
                {% if request.user|has_group:"teacher" or request.user|has_group:"head_teacher" %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle active" href="#" id="navbarDropdown" role="button"
                        data-bs-toggle="dropdown" aria-expanded="false">
                        Ваше расписание
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="/schedule/teacher_schedule/{{ request.user.id }}/1/">на первую
                                четверть</a></li>
                        <li><a class="dropdown-item" href="/schedule/teacher_schedule/{{ request.user.id }}/2/">на вторую
                                четверть</a></li>
                        <li><a class="dropdown-item" href="/schedule/teacher_schedule/{{ request.user.id }}/3/">на третью
                                четверть</a></li>
                        <li><a class="dropdown-item" href="/schedule/teacher_schedule/{{ request.user.id }}/4/">на
                                четвертую четверть</a></li>
                    </ul>
                </li>
                {% endif %}
            </ul>
        </div>
        <div class="navbar-text ms-auto me-0 ">
            <a class="nav-link" href="/account/">Здравствуйте, {{ request.user.first_name }}.</a>
        </div>
        <div class="navbar-text ms-3 me-0">
            <a class="nav-link" href="/logout/">Выйти</a>
        </div>
        <button class="navbar-toggler ms-3" type="button" data-bs-toggle="collapse"
            data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
            aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
    </div>
</nav>
{% endblock navbar %}

{% block content %}
<div style="height: 90vh;" class="d-flex flex-column align-items-center justify-content-center">
    <div class="row">
        <div class="col-12">
            <h1>Добро пожаловать.</h1>
            <h2>Используйте меню сверху для навигации.</h2>
        </div>
    </div>
</div>
{% endblock content %}

StudentJournal/users/templates/login.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% load static %}

{% block content %}
<div style="height: 100vh;" class="d-flex flex-column align-items-center justify-content-center">
    <div class="row">
        <div class="col-12">
            <form action="/login/" method="post" class="form" autocomplete="off">
                {% csrf_token %}
                <h4 class="mt-3 mb-3">Войти в систему:</h4>
                {{ form }}
                <button type="submit" class="btn btn-primary">Войти</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

StudentJournal/users/templates/studied_disciplines.html
{% extends "index.html" %}
{% load django_bootstrap5 %}
{% load static %}
{% load filters %}

{% block content %}
<div class="container">
    <div class="row mb-3 mt-3">
        <div class="col-md-5">
            <h4 class="mb-3">Выбор изучаемых дисциплин для класса {{ form.class_num.value }}</h4>
            <form method="post" action="/classes/studied_disciplines/{{ form.class_num.value }}/">
				{% csrf_token %}
                {{ form.class_num }}
                {{ form.studied_disciplines }}
                {{ form.errors }}
                <button class="btn btn-light mb-3" type="submit">Сохранить</button>
            </form>
            <p>Изменение изучаемых предметов не приведет к изменению расписания.</p>
        </div>
    </div>
</div>
{% endblock content %}